images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "v1.0.0"

- name: cloud-controller-manager
  sourceRepository: github.com/tidbcloud/kubernetes
  repository: gcr.io/pingcap-public/k8s/hyperkube
  tag: "v1.16.17"
  targetVersion: "< 1.17"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-aws
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-aws
  tag: "v1.17.4"
  targetVersion: "1.17.x"
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-aws
  repository: gcr.io/pingcap-public/kubernetes/cloud-provider-aws
  tag: "v1.18.0"
  targetVersion: ">= 1.18"
- name: machine-controller-manager
  sourceRepository: github.com/pingcap/machine-controller-manager
  repository: gcr.io/pingcap-public/gardener/machine-controller-manager
  tag: "v0.29.0-dev.3"
- name: aws-lb-readvertiser
  sourceRepository: github.com/gardener/aws-lb-readvertiser
  repository: eu.gcr.io/gardener-project/gardener/aws-lb-readvertiser
  tag: "0.6.0"

- name: csi-driver
  sourceRepository: github.com/kubernetes-sigs/aws-ebs-csi-driver
  repository: amazon/aws-ebs-csi-driver
  tag: "v0.9.0"
- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: "v1.6.0"
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: "v2.2.0"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: "v2.1.1"
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: quay.io/k8scsi/csi-resizer
  tag: "v0.5.0"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/snapshot-controller
  tag: "v2.1.1"
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: "v1.3.0"
- name: csi-liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: quay.io/k8scsi/livenessprobe
  tag: "v2.0.0"
